#!/bin/bash

set -o pipefail

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

source $SCRIPTDIR/validation.sh
source $SCRIPTDIR/common.sh

early_deploy_validation

if [[ -z ${AGENT_E2E_TEST_SCENARIO} && -z ${AGENT_E2E_TEST_SCENARIO_INSTALL_CONFIG_AGENT_CONFIG}]]; then
    echo "Either set AGENT_E2E_TEST_SCENARIO or AGENT_E2E_TEST_SCENARIO_INSTALL_CONFIG_AGENT_CONFIG env var in the config_<USER>.sh file."
    echo " Currently, both are missing or empty."
    echo "AGENT_E2E_TEST_SCENARIO Supported values: COMPACT_IPV4, COMPACT_IPV6, HA_IPV4, HA_IPV6, SNO_IPV4, SNO_IPV6."
    echo "AGENT_E2E_TEST_SCENARIO_INSTALL_CONFIG_AGENT_CONFIG Supported values: "
    echo "\n\tBAREMETAL_COMPACT_IPV4, BAREMETAL_COMPACT_IPV6, BAREMETAL_HA_IPV4, BAREMETAL_HA_IPV6, BAREMETAL_SNO_IPV4, BAREMETAL_SNO_IPV6."
    echo "\n\tVSPHERE_COMPACT_IPV4, VSPHERE_COMPACT_IPV6, VSPHERE_HA_IPV4, VSPHERE_HA_IPV6, VSPHERE_SNO_IPV4, VSPHERE_SNO_IPV6."
    echo "\n\tNONE_COMPACT_IPV4, NONEL_COMPACT_IPV6, NONE_HA_IPV4, NONE_HA_IPV6, NONE_SNO_IPV4, NONE_SNO_IPV6."
    exit 1
fi

if [[ ! -z ${AGENT_E2E_TEST_SCENARIO} && ! -z ${AGENT_E2E_TEST_SCENARIO_INSTALL_CONFIG_AGENT_CONFIG}]]; then
    echo "Either set AGENT_E2E_TEST_SCENARIO or AGENT_E2E_TEST_SCENARIO_INSTALL_CONFIG_AGENT_CONFIG env var in the config_<USER>.sh file."
    echo " Currently, both are set."
    echo "AGENT_E2E_TEST_SCENARIO Supported values: COMPACT_IPV4, COMPACT_IPV6, HA_IPV4, HA_IPV6, SNO_IPV4, SNO_IPV6."
    echo "AGENT_E2E_TEST_SCENARIO_INSTALL_CONFIG_AGENT_CONFIG Supported values: "
    echo "\n\tBAREMETAL_COMPACT_IPV4, BAREMETAL_COMPACT_IPV6, BAREMETAL_HA_IPV4, BAREMETAL_HA_IPV6, BAREMETAL_SNO_IPV4, BAREMETAL_SNO_IPV6."
    echo "\n\tVSPHERE_COMPACT_IPV4, VSPHERE_COMPACT_IPV6, VSPHERE_HA_IPV4, VSPHERE_HA_IPV6, VSPHERE_SNO_IPV4, VSPHERE_SNO_IPV6."
    echo "\n\tNONE_COMPACT_IPV4, NONEL_COMPACT_IPV6, NONE_HA_IPV4, NONE_HA_IPV6, NONE_SNO_IPV4, NONE_SNO_IPV6."
    exit 1
fi
